### ISSUE TITLE
Including this library breaks fadeIn function

### ISSUE THREAD

**Issue by Shnatsel** [heygrady/transform#1]
Including this library disables animation in fadeIn() jquery function, while fadeTo() function works correctly.

**Comment by adaddinsane** [comment]
Use jQuery 1.4.2

**Comment by Shnatsel** [comment]
I'm using 1.4.2 already - actually, it's the only version I tested.

**Comment by Shnatsel** [comment]
I've tried Google's jQuiery which you included in your example. It's 160kb size instead of 70kb official library. But fadeIn() still doesn't work.

**Comment by heygrady** [comment]
I tracked this to $.inArray() always returning true for me. I worked around that function and it seems to be working much better. I'll post a new version soon.
