### ISSUE TITLE
the top and left properties missing when i use .animate({scale:[0.1,0.1]},10, function(){...}}) in IE

### ISSUE THREAD

**Issue by fanfree** [heygrady/transform#11]
top and left properties of div  missing when i use .animate({scale:[0.1,0.1]},10, function(){...}}) ,my div is:
    <DIV style="Z-INDEX: 100; POSITION: absolute; WIDTH: 360px; DISPLAY: none; HEIGHT: 244px; TOP: 205px; LEFT: 458px" id=onlineBuilder class=jwindow title="" jQuery1284151893520="119">
is bug?

**Comment by heygrady** [comment]
Please read this issue: It is not a bug.
http://github.com/heygrady/transform/issues#issue/6

**Comment by heygrady** [comment]
Also, read this explanation: http://github.com/heygrady/transform/issues#issue/3

In general it is courteous to read through the other bug reports before posting a new bug. Thanks for using my plugin!
