### ISSUE TITLE
transform origin

### ISSUE THREAD

**Issue by ezmilhouse** [heygrady/transform#12]
hey Grady,
i have the x/y offsets of all four corners of a rotated div, i also know the rotation angle and the original width/height (before rotation). is it possible to position e.x. a cloned div based on these values using your plugin?

thx, mil

**Comment by heygrady** [comment]
I don't understand your question. My plugin mimicks the CSS3 functionality for 2d transformation and allows for animation as well. It works in IE by using the Matrix plugin. You can clearly see on the wiki pages how to use it.

```
$('#some-element').transform({rotate: 33}); //should rotate the element 33deg
```
