### ISSUE TITLE
the last version of chrome (8.0.552) on mac change rotation origin ?

### ISSUE THREAD

**Issue by originaliko** [heygrady/transform#19]
I've been using transform to do rotation on element on web site i'm developing and suddenly today after updating chrome, my elements rotates not from the center but from the upper left corner. 
I tried using the origin setting  but all I got is "TypeError: Cannot read property '2' of null"

**Comment by originaliko** [comment]
I was using an outdated version of the plugin. nevermind.

**Comment by heygrady** [comment]
Glad I could help :)
