### ISSUE TITLE
Apparently kills the animate function...

### ISSUE THREAD

**Issue by adaddinsane** [heygrady/transform#2]
This is a perfect match for something I'm doing - I need to create a constant rotation to replace some Flash that I can't (and don't want to) support - and I'm getting nothing.

I know - I can see it working in your demo.

Here's what I've got: I've tried it with jQuery 1.2.6 and 1.3.2, using both these I can animate a DIV so that if I click it it moves 500px to the left.

If I load up your transform code, the animate function ceases to work. That's not even calling any code in transform, it's just .animate({left:500}) no longer works. I remove the transform code, and it works again. I've tried versions 0.5.1 and 0.6.1, with the same result.

I am working in a Drupal environment, but when the code failed to work I stripped it back to the minimum so that's probably not relevant.

**Comment by jacobdubail** [comment]
I have the same exact problem.  All of my animations are working fine... until I add the transform plugin to the page.  I never call upon it, either.  removing the plugin from the page makes everything work again...

**Comment by adaddinsane** [comment]
Okay, it's because you need jQuery 1.4.2 - if you have that version it works.

**Comment by jacobdubail** [comment]
I am using jQuery 1.4.2.  
http://jacobdubail.com/jacobdubail/examples/crazydots/index2.html is broken.  All I've done is include the transform plugin.
http://jacobdubail.com/jacobdubail/examples/crazydots/index.html works.  transform plugin is not included.

**Comment by adaddinsane** [comment]
Well, it's not my code - I upgraded to 1.4.2 and it works for me.

I suggest you check the jQuery that's being loaded on the demo pages and compare with what your pages are loading.

**Comment by Shnatsel** [comment]
I've checked jQuiery files you included - they are identical.

**Comment by jacobdubail** [comment]
Thanks for noticing.  I even downloaded a fresh copy of both jQuery 1.4.2 and Transform 0.6.1(?).  Same problem.  Strange that I don't even have to call the plugin for everything to blow up.  All I have to do is include it on the page...

Thanks for your help!

**Comment by heygrady** [comment]
This should be fixed now.

**Comment by jacobdubail** [comment]
I'll test it asap and report back.  Thanks!!!

**Comment by jacobdubail** [comment]
Works beautifully!  Thank you so much!

http://jacobdubail.com/jacobdubail/examples/crazydots/index2.html
