### ISSUE TITLE
doesn't set css property

### ISSUE THREAD

**Issue by gauthierm** [heygrady/transform#20]
This plugin is just setting an element attribute called data-transform in webkit and gecko. It should be setting the css property.

**Comment by heygrady** [comment]
Can you provide an example? I've been using this plugin in testing for months and I test in Webkit and Gecko browsers. Is there a chance that you're not setting units?

```
$('example').css({rotate: 30}); // doesn't do much
$('example').css({rotate: '30deg'}); // rotates 30deg
```

But that's to be expected.
    <style>
        #example1 {
            -moz-transform: rotate(30); /\* doesn't do much _/
        }
        #example2 {
            -moz-transform: rotate(30deg); /_ rotates 30deg */
        }
    </style>
