### ISSUE TITLE
Rotation animation in IE 6-9 - Transparent png issue

### ISSUE THREAD

**Issue by jacobdubail** [heygrady/transform#22]
Hey Grady,

Lovin this plugin the more I use it.  Pretty slick.

The only issue I can find is that transparent images that whose rotation is animated get all kinds a jack'd up.  You can see an example here: http://in-flow.co/

Is this a known issue?  I couldn't find any docs on it.

Many thanks!

**Comment by heygrady** [comment]
The transparency should be better in IE9. But in IE8 and below applying a filter to a transparent PNG will cause issues. Essentially the partially transparent pixels turn black. You can actually fix the issue by applying a background color but that isn't always desirable.

**Comment by jacobdubail** [comment]
Bummer, but good to know.  Thanks for the reply!

**Comment by heygrady** [comment]
I just saw something in a library called "ColorBox" that appears to have a fix for the black halo in IE 6-8.

https://github.com/jackmoore/colorbox/blob/master/example1/colorbox.css#L56
