### ISSUE TITLE
Firefox Scaling - Image Position

### ISSUE THREAD

**Issue by jclusso** [heygrady/transform#24]
If you scale an Image and than use jquery.position() it returns the wrong position because of something to do with the scaling transformation.

**Comment by heygrady** [comment]
Please test this using the standard CSS for Firefox and see if it's Firfox or my library. I suspect it's Firefox, although it should be reporting the original position, not the transformed position.

**Comment by jclusso** [comment]
i fixed this by changing the transform origin to [0,0]. This causes the image position not to change and instead transform to the corner. If the origin is not set the image transforms towards its center and the position changes but for some reason in firefox, jquery does not see this change when you use position.

**Comment by heygrady** [comment]
https://developer.mozilla.org/En/CSS/-moz-transform-origin
By default the origin is 50% 50% according to the manual.
