### ISSUE TITLE
reflect false not working in anim sequence

### ISSUE THREAD

**Issue by danpep** [heygrady/transform#26]
Thanks for this plugin, seems really great. I'm trying to get something to rotate 360 degrees, reflecting on the 180 and back again. Seems like once you reflect, you cant reflect back as an animation.

how would you reflect back during an animation sequence.  E.g.:

$anim.animate({rotate: "+=180deg", reflectY: true}, {'duration': 1000})
.animate({rotate: "+=180deg", reflectY:false}, {'duration': 1000})

**Comment by heygrady** [comment]
http://jsfiddle.net/heygrady/duV8H/

The reflect properties are not part of the spec and were added for convenience. You can accomplish the same thing using the matrix property. See the JS fiddle above.

**Comment by danpep** [comment]
Nice, I actually got it working... the matrix was a little beyond me... I
forgot my linear algebra.

Thanks for the response.
