### ISSUE TITLE
RotateX, RotateY,

### ISSUE THREAD

**Issue by jlukic** [heygrady/transform#5]
RotateX and RotateY arent supported by your library, might be nice to have on to-do.  :D

**Comment by heygrady** [comment]
Those are 3D functions that are only supported by WebKit. The purpose of this library is to support 2D transformations in IE, Mozilla, WebKit and Opera in the versions that support it.

**Comment by jlukic** [comment]
Agreed, no cross-browser support for transforms yet, but I'm working on an iPad/iPhone site with 3d transforms so that's why i posited the request. I monkey-patched it for now but certainly would be nice for future 3D dev, I'd be extremely surprised if this doesnt land in minefield sometime soon.

**Comment by MrTomAsh** [comment]
Same as -webkit-perspective from Safarii WebKit.

**Comment by heygrady** [comment]
The safari-only 3d functions will not be supported by this library.

**Comment by MrTomAsh** [comment]
Maybe in next 3D libary you made.
