### ISSUE TITLE
Transforms over writing one another

### ISSUE THREAD

**Issue by Charuru** [heygrady/transform#8]
Hi, if I set a transform to say, scale, and then later on another command transforms the element with rotate, the latter transform will over write the previous transform rather than adding it as a second property. I don't think that's how it's supposed to work.

Please advise, thanks!

**Comment by heygrady** [comment]
Well, it is intended to work that way but there's an option to change that behavior. The thinking is that if you added a transform attribute in CSS it would overwrite, not augment. I need to document the options.

```
$('#mydiv').transform({scale: 1.5});
$('#mydiv').transform({skew: [45, 33]}); // removes scale
$('#mydiv').transform({scale: 1.5}, {preserve: true}); // preserves the skew
```

**Comment by Charuru** [comment]
Thanks. Animate on the other hand does not overwrite right? This is reliable behavior?

**Comment by heygrady** [comment]
Animate doesn't overwrite. Although I was considering having it overwrite on the first frame. It made sense to me but I'm open to suggestions.

**Comment by Charuru** [comment]
Thanks for the great plugin. I don't think doing different transforms should overwrite the previous ones, I think having multiple transforms on one element is a much more frequent usecase than someone needing to overwrite the previous transform with a different transform. However I understand what you mean by having the CSS disagree with me. I don't really know what would be more consistent.

It should also definitely not overwrite the first frame. I can just imagine it, having animated an element to a position, and then wanting to animate it some more, but have it pop back to initial start? I don't think that makes sense.

I don't really know, but I'm satisfied with the status quo. Thanks.
