### ISSUE TITLE
Don't work on <canvas> and <img> elements

### ISSUE THREAD

**Issue by MrTomAsh** [heygrady/transform#9]
When try to transform any canvas or img (by Id or Class) - just nothing happen.

**Comment by heygrady** [comment]
Really? It should work just fine on images. Which browser are you using? What code did you try? Please make it easier for me to help you.

```
<!-- This will work in FF 3.5+ -->
<img src="http://www.iconarchive.com/icons/visualpharm/animals/256/Elephant-icon.png" style="-moz-transform: rotate(45deg);" />
<script>
    // we can also do this in JavaScript
    $('img').transform({scale: 1.5, skew: [33, 33]});
</script>
```

http://wiki.github.com/heygrady/transform/

**Comment by MrTomAsh** [comment]
You're right - it's working. Maybe it's not working for me before because I try to transform element witch is create in JS.

I'm working at my new site and need to transform the reflection of my projects. Unfortunately I don't know Canvas so much to do it on it.

**Comment by MrTomAsh** [comment]
I make another test - it's work for my in canvas but not on canvas (id/class) creating by JS.

Work:
HTML create by JS:
< canvas id="reflect[0]">< /canvas>

JS:
 $('canvas').transform({scale: 1.5, skew: [33, 33]});

Didn't work:
HTML create by JS:
< canvas id="reflect[0]">< /canvas>

JS:
 $('#reflect[0]').transform({scale: 1.5, skew: [33, 33]});

Found the solution!

Work on:
HTML create by JS:
< canvas id="reflect0">< /canvas>

JS:
 $('#reflect0').transform({scale: 1.5, skew: [33, 33]});

**Comment by dylanharrington** [comment]
'#reflect[0]' isn't returning any elements but 'canvas' is, so it seems like it's just an issue with your selectors / your ids aren't compatible with jQuery.

for instance, the below code works just fine in my firebug console:
jQuery('.perspective canvas').transform({scale: 1.5, skew: [33, 33]}); and jQuery('.whatever').transform({scale: 1.5, skew: [33, 33]}); works if I give one of the canvas elements a class of 'whatever'.

**Comment by MrTomAsh** [comment]
Thanks! Issue closed.

**Comment by MrTomAsh** [comment]
If you have a moment - look on my site. Elements transform and animate but sometimes they get a wrong scale. Try few times. And if you wait while (about 3-4 sec) it gets right scale (in debug mode everything going mad for 1s like searching the right number).

Chome 6.0.490.1 dev / MacOS X 10.6.4
